name: Learn actions

on: push

jobs:
  prepare:
    name: prepare
    runs-on: macOS-latest
    steps:
      - name: Pulling files
        run: |
          # wget https://api.modpacks.ch/public/modpack/5/121/server/mac
          # chmod +x mac
          # ./mac 5
          touch file.txt
          echo test > file.txt
  pack:
    name: pack
    runs-on: macOS-latest
    needs: prepare
    steps:
      - name: Packing
          run: |
            cat file.txt